#!/bin/bash

#                          _      _
#                         (_)    | |
#  _   _  __ _ _ __  _ __  _  ___| | __
# | | | |/ _` | '_ \| '_ \| |/ __| |/ /
# | |_| | (_| | | | | | | | | (__|   <
#  \__, |\__,_|_| |_|_| |_|_|\___|_|\_\
#   __/ |
#  |___/
#
# credit: adi1090x (https://github.com/archcraft-os/archcraft)

##---------- launchers & menus ----------##

# removal seems to break "super" as launcher hotkey
alt + F1
	sh ~/.config/bspwm/rofi/bin/launcher

super + n
	nmd

super + {w,m,x,r,s,t}
	sh ~/.config/bspwm/rofi/bin/{windows,music,powermenu,asroot,screenshot,themes}

##---------- application shortcuts ----------##

super + Return
	bspterm

super + shift + {f,w,e}
	{pcmanfm,brave,code}

##---------- media control ----------##

# screenshot
Print
	scrot 'Screenshot_%Y-%m-%d-%S_$wx$h.png' -e 'mv $f $$(xdg-user-dir PICTURES) ; viewnior $$(xdg-user-dir PICTURES)/$f'

# 5 sec delay
alt + Print
	scrot -d 5 'Screenshot_%Y-%m-%d-%S_$wx$h.png' -e 'mv $f $$(xdg-user-dir PICTURES) ; viewnior $$(xdg-user-dir PICTURES)/$f'

# brightness
XF86MonBrightness{Up,Down}
	backlight{-up,-down}

# volume
XF86Audio{RaiseVolume,LowerVolume}
	volume{-up,-down}

# mute
XF86AudioMute
	amixer set Master toggle

# music control
XF86Audio{Next,Prev,Play,Stop}
	~/.config/bspwm/scripts/player-mpris-tail.py {next,previous,toggle,stop}

##---------- system ----------##

# lockscreen
super + l
    betterlockscreen -l

# reload keybindings
ctrl + alt + Escape
	pkill -USR1 -x sxhkd

# restart bspwm
ctrl + alt + r
	bspc wm -r


##---------- window management ----------##

# close window
super + c
	bspc node -c

# swap window to position
super + {_,shift + }{Left,Down,Up,Right}
	bspc node -{f,s} {west,south,north,east}

# Send focused window to another workspace
super + {_,shift + }{1-8}
	bspc {desktop -f,node -d} '^{1-8}'

# fullscreen
super + f
	bspc desktop -l next

# switch workspace
ctrl + super + {Left,Right}
	bspc desktop -f {prev.local,next.local}

# sticky window
ctrl + super + s
	bspc node -g sticky

# split horizontal, vertical or cancel
super + {h,v,q}
	bspc node -p {east,south,cancel}

# preselect the ratio
super + ctrl + {1-9}
	bspc node -o 0.{1-9}

## resize windows
super + alt + {Left,Down,Up,Right}
  	bspc node -z {left -20 0 || bspc node -z right -20 0, \
                bottom 0 20 || bspc node -z top 0 20,\
                top 0 -20 || bspc node -z bottom 0 -20,\
                right 20 0 || bspc node -z left 20 0}