#!/bin/bash

#                          _      _
#                         (_)    | |
#  _   _  __ _ _ __  _ __  _  ___| | __
# | | | |/ _` | '_ \| '_ \| |/ __| |/ /
# | |_| | (_| | | | | | | | | (__|   <
#  \__, |\__,_|_| |_|_| |_|_|\___|_|\_\
#   __/ |
#  |___/
#
# credit: adi1090x (https://github.com/archcraft-os/archcraft)

## Environment
export PATH="${PATH}:$HOME/.config/bspwm/bin"

## Get colors from .Xresources -------------------------------#
xrdb ~/.Xresources
getcolors () {
	FOREGROUND=$(xrdb -query | grep 'foreground:'| awk '{print $NF}')
	BACKGROUND=$(xrdb -query | grep 'background:'| awk '{print $NF}')
	BLACK=$(xrdb -query | grep 'color0:'| awk '{print $NF}')
	RED=$(xrdb -query | grep 'color1:'| awk '{print $NF}')
	GREEN=$(xrdb -query | grep 'color2:'| awk '{print $NF}')
	YELLOW=$(xrdb -query | grep 'color3:'| awk '{print $NF}')
	BLUE=$(xrdb -query | grep 'color4:'| awk '{print $NF}')
	MAGENTA=$(xrdb -query | grep 'color5:'| awk '{print $NF}')
	CYAN=$(xrdb -query | grep 'color6:'| awk '{print $NF}')
	WHITE=$(xrdb -query | grep 'color7:'| awk '{print $NF}')
}
getcolors

## Configurations -------------------------------#

# 4 workspaces on each monitor, displayport is main and hdmi second

# TODO: works only on my desktop setup, should be generic for every setup

bspc monitor DP-5 -d 'web' 'files' 'media' 'social'
bspc monitor HDMI-0 -d 'coding' 'VI' 'VII' 'VIII'

bspc config border_width 1
bspc config window_gap 10
bspc config split_ratio 0.50

bspc config focused_border_color "$BLUE"
bspc config normal_border_color "$BACKGROUND"
bspc config active_border_color "$MAGENTA"
bspc config presel_feedback_color "$GREEN"

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true


## Window rules -------------------------------#

# remove all rules first
bspc rule -r *:*

# assign windows to their default workspaces

declare -a desktop1=(Brave-browser)

declare -a desktop2=(Pcmanfm)

declare -a desktop3=(vlc)

declare -a desktop4=(whatsdesk)

declare -a desktop5=(Code Atom)

declare -a desktop6=()

declare -a desktop7=()

declare -a desktop8=()

# manually set rules
# TODO: surely there is a more efficient dynamic solution

for i in ${desktop1[@]}; do
	bspc rule -a $i desktop='^1' follow=on focus=on; done

for i in ${desktop2[@]}; do
  bspc rule -a $i desktop='^2' follow=on focus=on; done

for i in ${desktop3[@]}; do
	bspc rule -a $i desktop='^3' follow=on focus=on; done

for i in ${desktop4[@]}; do
	bspc rule -a $i desktop='^4' follow=on focus=on; done

for i in ${desktop5[@]}; do
	bspc rule -a $i desktop='^5' follow=on focus=on; done

for i in ${desktop6[@]}; do
	bspc rule -a $i desktop='^6' follow=on focus=on; done

for i in ${desktop7[@]}; do
	bspc rule -a $i desktop='^7' follow=on focus=on; done

for i in ${desktop8[@]}; do
	bspc rule -a $i desktop='^8' follow=on focus=on; done

# spotify needs to be set manually via script
bspc config external_rules_command "$HOME/.config/bspwm/scripts/fix_spotify.sh"

## Autostart -------------------------------#

# Kill if already running
killall -9 sxhkd xsettingsd dunst xfce4-power-manager

# Lauch notification daemon
dunst \
-geom "280x50-10+40" -frame_width "1" -font "Iosevka Custom 9" \
-lb "$BACKGROUND" -lf "$FOREGROUND" -lfr "$BLUE" \
-nb "$BACKGROUND" -nf "$FOREGROUND" -nfr "$BLUE" \
-cb "$BACKGROUND" -cf "$RED" -cfr "$RED" &

# Lauch keybindings daemon
sxhkd &

# Enable Super Keys For Menu
ksuperkey -e 'Super_L=Alt_L|F1' &
ksuperkey -e 'Super_R=Alt_L|F1' &

# Enable power management
xfce4-power-manager &

# Fix cursor
xsetroot -cursor_name left_ptr

# Restore wallpaper
bash $HOME/.fehbg

# Start bspwm scripts
bspcolors
bspcomp
bspbar &

# Issue Tracker (Don't Remove IT)
issue_tracker.sh
